name: rasa
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::python=3.10.12
  - conda-forge::psycopg2=2.9.3
  - conda-forge::langchain=0.0.340
  - conda-forge::pip=23.3.1
  - conda-forge::python-dotenv
  - conda-forge::sentence-transformers=2.2.2
  - pip:
    - rasa==3.6.14